In [1]:
import os
from importlib import reload
from datasets import api
from datasets import aws_utils
import global_vars
reload(api)
reload(aws_utils)
reload(global_vars)

data_dir = os.environ.get("DATA_HOME") or global_vars.DEFAULT_DATA_DIR
# Downloads data into `data_dir` if needed and loads into memory
api.load_all(data_dir)
data = api.data

mlo_weekly_co2.csv skipped - already exists on filesystem
statcan_leading_cause_of_death.csv skipped - already exists on filesystem
...Loading mlo_weekly_co2.csv at /home/d0nkrs/mlo_weekly_co2.csv
...Loading statcan_leading_cause_of_death.csv at /home/d0nkrs/statcan_leading_cause_of_death.csv

In [2]:
api.ppm_biweekly_average().head()
api.ppm_monthly_average().head()
api.ppm_yearly_average().tail()

    year         ppm
42  2016  404.258269
43  2017  406.570943
44  2018  408.553654
45  2019  411.470192
46  2020  413.877273

In [3]:
api.ppm_at("2020-03")

,date,ppm,1 yr ago.,10 yr ago,since 1800,# days,year,month,day,decimal
2388,2020-02-23,413.72,412.25,388.72,132.73,7,2020,2,23,2020.1462
2389,2020-03-01,413.87,411.91,391.38,132.75,7,2020,3,1,2020.1653
2390,2020-03-08,414.11,412.57,391.27,132.82,6,2020,3,8,2020.1844

In [4]:
api.leading_cause_of_death_by_year(2019)

,REF_DATE,GEO,Leading causes of death (ICD-10),VALUE
5,2015,"Canada, place of residence",Malignant neoplasms [C00-C97],77054
35,2015,"Canada, place of residence","Diseases of heart [I00-I09, I11, I13, I20-I51]",51534
45,2015,"Canada, place of residence",Cerebrovascular diseases [I60-I69],13795
65,2015,"Canada, place of residence",Chronic lower respiratory diseases [J40-J47],12573
95,2015,"Canada, place of residence","Accidents (unintentional injuries) [V01-X59, Y...",11833
55,2015,"Canada, place of residence",Influenza and pneumonia [J09-J18],7630
15,2015,"Canada, place of residence",Diabetes mellitus [E10-E14],7172
25,2015,"Canada, place of residence",Alzheimer's disease [G30],6587
105,2015,"Canada, place of residence","Intentional self-harm (suicide) [X60-X84, Y87.0]",4405
75,2015,"Canada, place of residence","Chronic liver disease and cirrhosis [K70, K73-...",3176
85,2015,"Canada, place of residence","Nephritis, nephrotic syndrome and nephrosis [N...",3129
115,2015,"Canada, place of residence","Assault (homicide) [X85-Y09, Y87.1]",456